#!/bin/bash


#	Just a script which helps configure my preferences
#	Mostly it helps to lock the pen to only one monitor,
#		and maps drawpad/pen buttons for me
#	Added some CLI argument parsing because monitors/etc
#		are different on different workstations


#	Globals
THIS_APP_NAME="Drawpad Setup"


#
log()
{
	echo "[$THIS_APP_NAME] $1"
	logger "[$THIS_APP_NAME] $1"
}
complain()
{
	logger -s "[$THIS_APP_NAME] $1"
	notify-send "[$THIS_APP_NAME] $1"
}
quit()
{
	echo
	if [ "$1" != "" ];then
		log "Quitting: $1"
	else
		log "Quitting"
	fi

	sleep 30
	exit 0
}
die()
{
	complain "Fatal: $1"
	sleep 30
	exit 1
}


######################
#	Default values


# Change MONITOR to what monitor you want from running command: xrandr
#MONITOR="DP-1"
MONITOR="HDMI-1"


# Pen and Pad names can be found with xinput
PAD_NAME='Wacom Intuos BT S Pad pad'
PEN_NAME='Wacom Intuos BT S Pen stylus'


# The hotkey gromit-mpx is expecting
GROMIT_HOTKEY="F9"


######################


#	Pull CLI
log "Begin parsing CLI arguments"
while [ "$#" -gt 0 ]
do
	ARG="$1"
	log "Current argument: $ARG"

	case "$ARG" in

		--help|-h|?)
			log ""
			log "******************************"
			log "***** Drawpad Setup Menu *****"
			log "--info            => Output some useful information"
			log "--monitor         => Specify the monitor to use (Currently: $MONITOR)"
			log "--no-monitor      => Don't configure a monitor to use"
			log "--pad             => Set the pad name"
			log "--pen             => Set the pen name"
			log "--gromit-hotkey   => Specify which hotkey this installation of gromit-mpx uses (Currently: $GROMIT_HOTKEY)"
			shift
			quit
			;;


		--info)
			log "Showing some helpful information"
			xrandr
			xinput
			log "Reminder: You can use xev to determine button codes and such"
			log "Reminder: /usr/include/X11/keysymdef.h contains key definitions"
			shift
			quit
			;;


		--monitor|--display)
			MONITOR="$2"
			log "Setting monitor to: $MONITOR"
			shift
			shift
			;;


		--no-monitor|--no-display)
			MONITOR=""
			log "Setting monitor to: Don't set"
			shift
			;;


		--pad)
			PAD_NAME="$2"
			log "Setting pad to: $PAD_NAME"
			shift
			shift
			;;


		--pen)
			PEN_NAME="$2"
			log "Setting pen to: $PEN_NAME"
			shift
			shift
			;;


		--gromit-hotkey|--gromit-key)
			GROMIT_HOTKEY="$2"
			log "Will assign pad buttons for gromit hotkey: $GROMIT_HOTKEY"
			shift
			shift
			;;


		*)
			die "Unexpected argument: $ARG"
			;;
	esac
done
log "Finished parsing CLI arguments"


#	Grab the pen's proper ID and map it to the specified monitor (if applicable)
PEN_ID=`xinput | grep "$PEN_NAME" | cut -f 2 | cut -c 4-5`
log "Pen's proper ID: $PEN_ID"
if [ "$MONITOR" != "" ];then
	log "Asking xinput to map pen #$PEN_ID to monitor $MONITOR"
	xinput map-to-output "$PEN_ID" "$MONITOR" || die "xinput failed to map pen $PEN_ID to monitor $MONITOR, for some reason!"
	log "Done asking xinput to map pen #$PEN_ID to monitor $MONITOR"
else
	log "No monitor specified; Won't ask xinput to map pen to any particular monitor"
fi


# Hint: use xev to show key codes
# /usr/include/X11/keysymdef.h
log "Configuring pad buttons"
#xsetwacom list parameters
#xsetwacom list modifiers
#xsetwacom --get "$PEN_NAME" all
xsetwacom --set "$PAD_NAME" Button 1 key +control || die "Failed to set pad Button 1 to CONTROL key"
xsetwacom --set "$PAD_NAME" Button 2 key +control +shift || die "Failed to set pad Button 2 to ALT key"
xsetwacom --set "$PAD_NAME" Button 3 key "$GROMIT_HOTKEY" || die "Failed to set pad Button 3 to: $GROMIT_HOTKEY" # Gromit activate/deactivate key
xsetwacom --set "$PAD_NAME" Button 8 key +shift +"$GROMIT_HOTKEY" -shift -"$GROMIT_HOTKEY" || die "Failed to set pad Button 8 to SHIFT+${GROMIT_HOTKEY}" # Gromit clear screen

# Setup pen buttons
log "Configuring pen buttons"
xsetwacom --set "$PEN_NAME" Button 1 || die "Failed to set pen Button 1 to default"		# Button 1 is actually pressing the pen down on the pad
xsetwacom --set "$PEN_NAME" Button 2 key +shift  || die "Failed to set pen Button 2 to SHIFT"	# Button 2 is main button click on pen
xsetwacom --set "$PEN_NAME" Button 3 || die "Failed to set pen Button 3 to default"	# Button 3 is back button click on pen


#
quit "Finished"



